[package]
name = "test_crate"
version = "0.0.0"
authors = ["Mike Lubinets <public@mersinvald.me>"]
edition = "2018"
publish = false

[dependencies]
autorand = { path = "../" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"